---
- name: Ensure Docker is installed and user is added to docker group
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      ansible.builtin.include_role:
        name: geerlingguy.docker
      vars:
        docker_users:
          - "{{ lookup('env', 'USER') }}"

    - name: Reconnect to the host
      ansible.builtin.meta: reset_connection

- name: Build and run Docker container
  hosts: all
  tasks:
    - name: Copy docker files to remote
      ansible.builtin.copy:
        src: docker/
        dest: /tmp/docker/
        mode: "0755"

    - name: Build Docker Image from local directory
      community.docker.docker_image:
        name: http_status_checker
        build:
          path: /tmp/docker/
        source: build

    - name: Run Docker Container
      community.docker.docker_container:
        name: http_status_checker
        image: http_status_checker
        state: started
        detach: false
      register: container_result

    - name: Show Docker logs
      ansible.builtin.debug:
        msg: "{{ container_result.container.Output }}"
